
version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/defualt.conf
    extra_hosts:
        - "fluentd:127.0.0.1"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: myaccount-api-nginx
        fluentd-async-connect: "true"
    network_mode: host
  
  fluentd:
    build: fluentd/
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    network_mode: host

